%% legend_RSED
% specification of reference legend for all animals

%
function legend = legend_RSED
% created at 2016/04/12 by Bas Kooijman

  %% Syntax
  % legend = <legend_RSED.m *legend_RSED*>

  %% Description
  % Specifies a reference legend for all animals
  %
  % Output
  %
  % * legend: (9,2) cell matrix with (marker, taxon)-pairs

  % type, size, linewidth, edge color and face color of a marker, taxon
  legend = {...
    {'o', 8, 3, [0 0 0], [0 0 0]}, 'Radiata'; ...
    {'o', 8, 3, [0 0 0], [0 0 1]}, 'Chaetognatha'; ...
    {'o', 8, 3, [0 0 1], [1 0 1]}, 'Spiralia'; ...
    {'o', 8, 3, [0 0 1], [0 0 1]}, 'Ecdysozoa'; ....
    {'o', 8, 3, [1 0 0], [1 0 1]}, 'Chondrichthyes'; ....
    {'o', 8, 3, [1 0 0], [0 0 1]}, 'Actinopterygii'; ....
    {'o', 8, 3, [1 0 0], [1 .5 .5]}, 'Mammalia'; ....
    {'o', 8, 3, [1 0 0], [1 0 0]}, 'Tetrapoda'; ....
    {'o', 8, 3, [1 0 0], [0 0 0]}, 'Deuterostomata'; ....
  };
end

