%% legend_hexa
% specification of a legend for hexapoda

%
function legend = legend_hexa
% created at 2016/04/23 by Bas Kooijman

  %% Syntax
  % legend = <legend_hexa.m *legend_hexa*>

  %% Description
  % Specifies a legend for hexapoda
  %
  % Output
  %
  % * legend: (10,2) cell matrix with (marker, taxon)-pairs

  % type, size, linewidth, edge color and face color of a marker, taxon
  legend = {...
    {'o', 8, 3, [0 0 0], [0 0 0]}, 'Chelicerata'; ...
    {'o', 8, 3, [0 0 0], [0 0 1]}, 'Crustacea'; ...
    {'o', 8, 3, [0 0 1], [0 0 0]}, 'Entognatha'; ....
    {'o', 8, 3, [0 0 1], [0 0 1]}, 'Thysanura'; ....
    {'o', 8, 3, [0 0 1], [1 0 1]}, 'Ephemeroptera'; ....
    {'o', 8, 3, [1 0 1], [0 0 1]}, 'Polyneoptera'; ....
    {'o', 8, 3, [1 0 1], [1 0 1]}, 'Paraneoptera'; ....
    {'o', 8, 3, [1 0 0], [1 0 0]}, 'Holometabola'; ....
    {'.', 16, 3, [0 0 1], [0 0 0]}, 'Ecdysozoa'; ....
    {'.', 8, 3, [0 0 0], [0 0 0]}, 'Animalia'; ....
  };
end
