%% legend_RSED
% specification of reference legend 

%
function legend = legend_RSED
% created at 2016/04/12 by Bas Kooijman

  %% Syntax
  % legend = <legend_RSED.m *legend_RSED*>

  %% Description
  % Specifies a reference legend
  %
  % Output
  %
  % * legend: (8,2) cell matix with marker, taxon pairs

  % type, size, linewidth, edge color and face color of a marker, taxon
  legend = {...
    {'o', 8, 3, [0 0 1], [0 0 1]}, 'Radiata'; ...
    {'o', 8, 3, [0 0 0], [0 0 0]}, 'Chaetognatha'; ...
    {'o', 8, 3, [1 0 1], [1 0 1]}, 'Spiralia'; ...
    {'o', 8, 3, [1 0 0], [1 0 0]}, 'Ecdysozoa'; ....
    {'o', 8, 3, [0 1 0], [.75 0 .75]}, 'Chondrichthyes'; ....
    {'o', 8, 3, [0 1 0], [1 0 1]}, 'Actinopterygii'; ....
    {'o', 8, 3, [0 1 0], [.75 0 0]}, 'Mammalia'; ....
    {'o', 8, 3, [0 1 0], [1 0 0]}, 'Tetrapoda'; ....
    {'o', 8, 3, [0 1 0], [0 1 0]}, 'Deuterostomata'; ....
  };
end

