//
// Copyright (c) 2006 by Conor O''Mahony.
// For enquiries, please email GubuSoft@GubuSoft.com
// Please keep all copyright notices below.
// Original author of TreeView script is Marcelino Martins.
// This document includes the TreeView script.
// The TreeView script can be found at http://www.TreeView.net.
// The script is Copyright (c) 2006 by Conor O''Mahony.
//
// You can find general instructions for this file at www.treeview.net.
//

USETEXTLINKS = 1
STARTALLOPEN = 0
USEFRAMES = 0
USEICONS = 0
WRAPTEXT = 1
PRESERVESTATE = 1
HIGHLIGHT = 1

foldersTree = gFld("<b>Mollusca</b>", "treeview_taxa.html")
L2 = insFld(foldersTree, gFld("Bivalvia", "treeview_taxa.html?pic=Bivalvia.png"))
L3 = insFld(L2, gFld("Veneroida", "treeview_taxa.html?pic=Veneroida.png"))
L4 = insFld(L3, gFld("Arcticidae", "treeview_taxa.html?pic=Arcticidae.png"))
L5 = insFld(L4, gFld("Arctica", "treeview_taxa.html?pic=Arctica.png"))
insDoc(L5, gLnk("S", "Arctica_islandica", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Arctica_islandica.html"))
L4 = insFld(L3, gFld("Cardiidae", "treeview_taxa.html?pic=Cardiidae.png"))
L5 = insFld(L4, gFld("Cerastoderma", "treeview_taxa.html?pic=Cerastoderma.png"))
insDoc(L5, gLnk("S", "Cerastoderma_edule", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Cerastoderma_edule.html"))
L4 = insFld(L3, gFld("Tellinidae", "treeview_taxa.html?pic=Tellinidae.png"))
L5 = insFld(L4, gFld("Macoma", "treeview_taxa.html?pic=Macoma.png"))
insDoc(L5, gLnk("S", "Macoma_balthica", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Macoma_balthica.html"))
L4 = insFld(L3, gFld("Solenidae", "treeview_taxa.html?pic=Solenidae.png"))
L5 = insFld(L4, gFld("Ensis", "treeview_taxa.html?pic=Ensis.png"))
insDoc(L5, gLnk("S", "Ensis_directus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Ensis_directus.html"))
L4 = insFld(L3, gFld("Veneridae", "treeview_taxa.html?pic=Veneridae.png"))
L5 = insFld(L4, gFld("Ruditapes", "treeview_taxa.html?pic=Ruditapes.png"))
insDoc(L5, gLnk("S", "Ruditapes_philippinarum", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Ruditapes_philippinarum.html"))
L3 = insFld(L2, gFld("Ostreoida", "treeview_taxa.html?pic=Ostreoida.png"))
L4 = insFld(L3, gFld("Ostreidae", "treeview_taxa.html?pic=Ostreidae.png"))
L5 = insFld(L4, gFld("Crassostrea", "treeview_taxa.html?pic=Crassostrea.png"))
insDoc(L5, gLnk("S", "Crassostrea_gigas", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Crassostrea_gigas.html"))
L5 = insFld(L4, gFld("Ostrea", "treeview_taxa.html?pic=Ostrea.png"))
insDoc(L5, gLnk("S", "Ostrea_edulis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Ostrea_edulis.html"))
L4 = insFld(L3, gFld("Pectinidae", "treeview_taxa.html?pic=Pectinidae.png"))
L5 = insFld(L4, gFld("Argopecten", "treeview_taxa.html?pic=Argopecten.png"))
insDoc(L5, gLnk("S", "Argopecten_purpuratus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Argopecten_purpuratus.html"))
L5 = insFld(L4, gFld("Pecten", "treeview_taxa.html?pic=Pecten.png"))
insDoc(L5, gLnk("S", "Pecten_maximus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Pecten_maximus.html"))
L3 = insFld(L2, gFld("Myoida", "treeview_taxa.html?pic=Myoida.png"))
L4 = insFld(L3, gFld("Myidae", "treeview_taxa.html?pic=Myidae.png"))
L5 = insFld(L4, gFld("Mya", "treeview_taxa.html?pic=Mya.png"))
insDoc(L5, gLnk("S", "Mya_arenaria", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Mya_arenaria.html"))
L3 = insFld(L2, gFld("Mytiloida", "treeview_taxa.html?pic=Mytiloida.png"))
L4 = insFld(L3, gFld("Mytilidae", "treeview_taxa.html?pic=Mytilidae.png"))
L5 = insFld(L4, gFld("Perna", "treeview_taxa.html?pic=Perna.png"))
insDoc(L5, gLnk("S", "Perna_viridis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Perna_viridis.html"))
L5 = insFld(L4, gFld("Mytilus", "treeview_taxa.html?pic=Mytilus.png"))
insDoc(L5, gLnk("S", "Mytilus_edulis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Mytilus_edulis.html"))
insDoc(L5, gLnk("S", "Mytilus_californianus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Mytilus_californianus.html"))
insDoc(L5, gLnk("S", "Mytilus_galloprovincialis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Mytilus_galloprovincialis.html"))
insDoc(L5, gLnk("S", "Mytilus_trossulus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Mytilus_trossulus.html"))
L5 = insFld(L4, gFld("Brachidontes", "treeview_taxa.html?pic=Brachidontes.png"))
insDoc(L5, gLnk("S", "Brachidontes_pharaonis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Brachidontes_pharaonis.html"))
L5 = insFld(L4, gFld("Mytilaster", "treeview_taxa.html?pic=Mytilaster.png"))
insDoc(L5, gLnk("S", "Mytilaster_minimus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Mytilaster_minimus.html"))
L2 = insFld(foldersTree, gFld("Gastropoda", "treeview_taxa.html?pic=Gastropoda.png"))
L3 = insFld(L2, gFld("Prosobranchia", "treeview_taxa.html?pic=Prosobranchia.png"))
L4 = insFld(L3, gFld("Neotaenioglossa", "treeview_taxa.html?pic=Neotaenioglossa.png"))
L5 = insFld(L4, gFld("Calyptraeidae", "treeview_taxa.html?pic=Calyptraeidae.png"))
L6 = insFld(L5, gFld("Crepidula", "treeview_taxa.html?pic=Crepidula.png"))
insDoc(L6, gLnk("S", "Crepidula_fornicata", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Crepidula_fornicata.html"))
L3 = insFld(L2, gFld("Heterobranchia", "treeview_taxa.html?pic=Heterobranchia.png"))
L4 = insFld(L3, gFld("Euopisthobranchia", "treeview_taxa.html?pic=Euopisthobranchia.png"))
L5 = insFld(L4, gFld("Aplysiidae", "treeview_taxa.html?pic=Aplysiidae.png"))
L6 = insFld(L5, gFld("Aplysia", "treeview_taxa.html?pic=Aplysia.png"))
insDoc(L6, gLnk("S", "Aplysia_californica", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Aplysia_californica.html"))
L5 = insFld(L4, gFld("Gymnosomata", "treeview_taxa.html?pic=Gymnosomata.png"))
L6 = insFld(L5, gFld("Clionidae", "treeview_taxa.html?pic=Clionidae.png"))
L7 = insFld(L6, gFld("Clione", "treeview_taxa.html?pic=Clione.png"))
insDoc(L7, gLnk("S", "Clione_limacina", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Clione_limacina.html"))
L4 = insFld(L3, gFld("Nudibranchia", "treeview_taxa.html?pic=Nudibranchia.png"))
L5 = insFld(L4, gFld("Tergipedidae", "treeview_taxa.html?pic=Tergipedidae.png"))
L6 = insFld(L5, gFld("Cuthona", "treeview_taxa.html?pic=Cuthona.png"))
insDoc(L6, gLnk("S", "Cuthona_nana", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Cuthona_nana.html"))
L4 = insFld(L3, gFld("Pulmonata", "treeview_taxa.html?pic=Pulmonata.png"))
L5 = insFld(L4, gFld("Lymnaeidae", "treeview_taxa.html?pic=Lymnaeidae.png"))
L6 = insFld(L5, gFld("Lymnaea", "treeview_taxa.html?pic=Lymnaea.png"))
insDoc(L6, gLnk("S", "Lymnaea_stagnalis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Lymnaea_stagnalis.html"))
L6 = insFld(L5, gFld("Stagnicola", "treeview_taxa.html?pic=Stagnicola.png"))
insDoc(L6, gLnk("S", "Stagnicola_palustris", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Stagnicola_palustris.html"))
L5 = insFld(L4, gFld("Planorbidae", "treeview_taxa.html?pic=Planorbidae.png"))
L6 = insFld(L5, gFld("Biomphalaria", "treeview_taxa.html?pic=Biomphalaria.png"))
insDoc(L6, gLnk("S", "Biomphalaria_glabrata", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Biomphalaria_glabrata.html"))
L6 = insFld(L5, gFld("Planorbis", "treeview_taxa.html?pic=Planorbis.png"))
insDoc(L6, gLnk("S", "Planorbis_planorbis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Planorbis_planorbis.html"))
L2 = insFld(foldersTree, gFld("Cephalopoda", "treeview_taxa.html?pic=Cephalopoda.png"))
L3 = insFld(L2, gFld("Sepiida", "treeview_taxa.html?pic=Sepiida.png"))
L4 = insFld(L3, gFld("Sepiidae", "treeview_taxa.html?pic=Sepiidae.png"))
L5 = insFld(L4, gFld("Sepia", "treeview_taxa.html?pic=Sepia.png"))
insDoc(L5, gLnk("S", "Sepia_officinalis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Sepia_officinalis.html"))
L3 = insFld(L2, gFld("Sepiolida", "treeview_taxa.html?pic=Sepiolida.png"))
L4 = insFld(L3, gFld("Sepiolidae", "treeview_taxa.html?pic=Sepiolidae.png"))
L5 = insFld(L4, gFld("Sepiola", "treeview_taxa.html?pic=Sepiola.png"))
insDoc(L5, gLnk("S", "Sepiola_atlantica", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Sepiola_atlantica.html"))
L5 = insFld(L4, gFld("Sepietta", "treeview_taxa.html?pic=Sepietta.png"))
insDoc(L5, gLnk("S", "Sepietta_obscura", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Sepietta_obscura.html"))
L5 = insFld(L4, gFld("Euprymna", "treeview_taxa.html?pic=Euprymna.png"))
insDoc(L5, gLnk("S", "Euprymna_hyllebergi", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Euprymna_hyllebergi.html"))
L3 = insFld(L2, gFld("Teuthida", "treeview_taxa.html?pic=Teuthida.png"))
L4 = insFld(L3, gFld("Loliginidae", "treeview_taxa.html?pic=Loliginidae.png"))
L5 = insFld(L4, gFld("Doryteuthis", "treeview_taxa.html?pic=Doryteuthis.png"))
insDoc(L5, gLnk("S", "Doryteuthis_pealei", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Doryteuthis_pealei.html"))
L3 = insFld(L2, gFld("Octopoda", "treeview_taxa.html?pic=Octopoda.png"))
L4 = insFld(L3, gFld("Octopodidae", "treeview_taxa.html?pic=Octopodidae.png"))
L5 = insFld(L4, gFld("Octopus", "treeview_taxa.html?pic=Octopus.png"))
insDoc(L5, gLnk("S", "Octopus_cyanea", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Octopus_cyanea.html"))
insDoc(L5, gLnk("S", "Octopus_maya", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Octopus_maya.html"))
insDoc(L5, gLnk("S", "Octopus_vulgaris", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/i_results_Octopus_vulgaris.html"))
